=== tests/cases/compiler/flowAfterFinally1.ts ===
declare function openFile(): void
>openFile : () => void

declare function closeFile(): void
>closeFile : () => void

declare function someOperation(): {}
>someOperation : () => {}

var result: {}
>result : {}

openFile()
>openFile() : void
>类型别名 :=> 无值
>openFile : () => void

try {
  result = someOperation()
>result = someOperation() : {}
>result : {}
>someOperation() : {}
>someOperation : () => {}

} finally {
  closeFile()
>closeFile() : void
>类型别名 :=> 无值
>closeFile : () => void
}

result // should not error here
>result : {}

