=== tests/cases/compiler/noErrorsInCallback.ts ===
class Bar {
>Bar : Bar

    constructor(public foo: string) { }
>foo : string
>类型别名 :=> 文字
}
var one = new Bar({}); // Error
>one : any
>类型别名 :=> 任意
>new Bar({}) : any
>类型别名 :=> 任意
>Bar : typeof Bar
>{} : {}

[].forEach(() => {
>[].forEach(() => {    var two = new Bar({}); // No error?}) : void
>类型别名 :=> 无值
>[].forEach : (callbackfn: (value: any, index: number, array: any[]) => void, thisArg?: any) => void
>[] : undefined[]
>forEach : (callbackfn: (value: any, index: number, array: any[]) => void, thisArg?: any) => void
>() => {    var two = new Bar({}); // No error?} : () => void

    var two = new Bar({}); // No error?
>two : any
>类型别名 :=> 任意
>new Bar({}) : any
>类型别名 :=> 任意
>Bar : typeof Bar
>{} : {}

});
 
