=== tests/cases/compiler/noErrorsInCallback.ts ===
class Bar {
>Bar : Bar

    constructor(public foo: string) { }
>foo : 文字
>类型别名 :=> 文字
}
var one = new Bar({}); // Error
>one : 任意
>类型别名 :=> 任意
>new Bar({}) : 任意
>类型别名 :=> 任意
>Bar : 类为 Bar
>{} : {}

[].forEach(() => {
>[].forEach(() => {    var two = new Bar({}); // No error?}) : 无值
>类型别名 :=> 无值
>[].forEach : (callbackfn: (value: 任意, index: 数字, array: 任意[]) => 无值, thisArg?: 任意) => 无值
>[] : 未定[]
>forEach : (callbackfn: (value: 任意, index: 数字, array: 任意[]) => 无值, thisArg?: 任意) => 无值
>() => {    var two = new Bar({}); // No error?} : () => 无值

    var two = new Bar({}); // No error?
>two : 任意
>类型别名 :=> 任意
>new Bar({}) : 任意
>类型别名 :=> 任意
>Bar : 类为 Bar
>{} : {}

});
 
